--

CREATE TABLE xmlfp (
  id INT PRIMARY KEY AUTO_INCREMENT,
  url VARCHAR(255) NOT NULL COMMENT 'Descriptor URL',
  xml TEXT NOT NULL COMMENT 'Descriptor XML',

  UNIQUE KEY (url)
) ENGINE = INNODB DEFAULT CHARSET=cp1251;