
DROP TABLE IF EXISTS autocomplete;
CREATE TABLE autocomplete (
  search_text VARCHAR(255),
  search_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cnt INT NOT NULL DEFAULT 1,

  PRIMARY KEY (search_text)
  )
ENGINE=INNODB
DEFAULT CHARSET=cp1251;