//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.07 at 04:03:05 AM MSD 
//


package info.xonix.zlo.search.xmlfp.xjccompiled.message;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}info"/>
 *         &lt;element ref="{}author"/>
 *         &lt;element ref="{}content"/>
 *       &lt;/all>
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ok"/>
 *             &lt;enumeration value="deleted"/>
 *             &lt;enumeration value="notExists"/>
 *             &lt;enumeration value="unknown"/>
 *             &lt;enumeration value="spam"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "message")
public class Message {

    @XmlElement(required = true)
    protected Info info;
    @XmlElement(required = true)
    protected Author author;
    @XmlElement(required = true)
    protected Content content;
    @XmlAttribute
    protected String status;

    /**
     * Gets the value of the info property.
     *
     * @return possible object is
     *         {@link Info }
     */
    public Info getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     *
     * @param value allowed object is
     *              {@link Info }
     */
    public void setInfo(Info value) {
        this.info = value;
    }

    /**
     * Gets the value of the author property.
     *
     * @return possible object is
     *         {@link Author }
     */
    public Author getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     *
     * @param value allowed object is
     *              {@link Author }
     */
    public void setAuthor(Author value) {
        this.author = value;
    }

    /**
     * Gets the value of the content property.
     *
     * @return possible object is
     *         {@link Content }
     */
    public Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     *
     * @param value allowed object is
     *              {@link Content }
     */
    public void setContent(Content value) {
        this.content = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
